// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc porm_V1.20

package tutorial

import (
	"context"
)

type GraphqlClientInterface interface {
	Do(ctx context.Context, query string, variables map[string]interface{}, v interface{}) error
	//  Sdl(ctx context.Context) error
}

func NewClient(client GraphqlClientInterface) *Queries {
	return &Queries{
		// e,
		client,
	}
}

type Queries struct {
	// e *engine.QueryEngine
	client GraphqlClientInterface
}
