// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc porm_V1.20
// source: Test3

package tutorial

import (
	"context"
	"fmt"
)

const test3 = `# name: Test3 
	query Test3 ($whe: PostWhereInput!, $tak: Int!) {
	findManyPost(where: $whe, take: $tak, skip: 0) {
		id
		published
		title
		author {
			desc
			id
		}
	}
}

	`

//,whe *PostWhereInput

//,whe *PostWhereInput,tak int32

func (t Queries) Test3(ctx context.Context, whe *PostWhereInput, tak int32) (res *Test3Response, err error) {

	input := map[string]interface{}{

		"whe": whe, //*PostWhereInput

		"tak": tak, //int32

	}
	qry, _ := InlineQuery(test3, input) //这里要优化？
	err = Do(ctx, t.e, qry, &res)
	if err != nil {
		fmt.Println(err)
	}
	return
}
