// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc porm_V1.20
// source: Test

package tutorial

import (
	"context"
	"fmt"

	"github.com/AnsonCode/porm/utils"
)

const test = `# name: Test 
	query Test ($param1: String!) {
	result: findUniquePost(where: {id:$param1}) {
		id
		createdAt
		updatedAt
		title
		published
		desc
	}
}

	`

//,param1 string

func (t Queries) Test(ctx context.Context, param1 string) (res *TestResponse, err error) {

	input := map[string]interface{}{

		"param1": param1, //string

	}
	qry, _ := utils.InlineQuery(test, input) //这里要优化？
	err = Do(ctx, t.e, qry, &res)
	if err != nil {
		fmt.Println(err)
	}
	return
}
