// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc porm_V1.20
// source: cusGet

package custom

import (
	"context"
	"fmt"
)

//# name: CusGet
const cusGet = `SELECT * FROM Post WHERE id= ${id} `

//,id string

func (t Queries) CusGet(ctx context.Context, id string) (res *CusGetResponse, err error) {
	input := map[string]interface{}{

		"id": id, //string

	}
	err = t.client.RawSQL(ctx, cusGet, input, &res)
	if err != nil {
		fmt.Println(err)
	}
	return
}
