// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc porm_V1.20

package custom

import (
	"encoding/json"
	"time"
)

type DateTime time.Time

const (
	timeFormart = "2006-01-02T15:04:05.000Z"
)

func (t *DateTime) UnmarshalJSON(data []byte) (err error) {
	now, err := time.ParseInLocation(`"`+timeFormart+`"`, string(data), time.Local)
	*t = DateTime(now)
	return
}

func (t DateTime) MarshalJSON() ([]byte, error) {
	b := make([]byte, 0, len(timeFormart)+2)
	b = append(b, '"')
	b = time.Time(t).AppendFormat(b, timeFormart)
	b = append(b, '"')
	return b, nil
}

func (t DateTime) String() string {
	return time.Time(t).Format(timeFormart)
}

type Json struct {
	json.RawMessage
}

// 枚举定义开始

// 结构定义开始

// OBJECT_Query_PART
type CusGetCusGetPostById struct {
	// -
	ID string `json:"id"`
	// -
	Title string `json:"title"`
	// -
	Desc *string `json:"desc"`
}

// res2_struct
type CusGetResponse struct {
	// -
	CusGetPostById []*CusGetCusGetPostById `json:"queryRaw"`
}
